name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
        - { version: "3.11.7", tag: "alpine-3.11.7" }
        - { version: "3.12.3", tag: "alpine-3.12.3" }
        - { version: "latest", tag: "alpine-latest" }
        - { version: "latest", tag: "latest" }
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup qemu
      uses: docker/setup-qemu-action@v1
    - name: setup buildx
      uses: docker/setup-buildx-action@v1
    - name: login dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build and push legacy
      uses: docker/build-push-action@v2
      with:
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: true
        tags: jipp13/fritzcollectd:${{ matrix.build.tag }}
        build-args: |
          version=${{ matrix.build.version }}
